apiVersion: apps/v1
kind: Deployment
metadata:
  name: testingphase-project-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testingphase-project
  template:
    metadata:
      labels:
        app: testingphase-project
    spec:
      containers:
      - name: testingphase-project-container
        image: testingphase_project:v1
        resources:
          limits:
            memory: "950Mi"
            cpu: "1000m"
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: testingphase-project-service
spec:
  selector:
    app: testingphase-project
  ports:
  - port: 1234
    targetPort: 8000
---
